# Generated by Django 5.1.4 on 2025-01-19 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks_tracker', '0003_comment_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to='comments_media/'),
        ),
    ]
